repos:
  - repo: https://github.com/ambv/black
    rev: 21.7b0
    hooks:
    - id: black
      types: [python]
      exclude: docs/
      args:
        - -S
  - repo: https://github.com/pycqa/isort
    rev: "5.8.0"
    hooks:
      - id: isort
